### ISSUE TITLE
Not able to use this along a logging implementation? (NLog, log4net, etc.)

### ISSUE THREAD

**Issue by RudeySH** [amrlafi/Glimpse.Common.Logging#1]
Can you use this package to display logs in Glimpse while also keeping Common.Logging acting as a facade to log in our log implementation of choice? Currently, it seems using this package means replacing NLog (or others) with a mere Glimpse tab, no persistence whatsoever. I was hoping to be able to log using NLog through Common.Logging, and being able to see the log in a Glimpse tab.

**Comment by amrlafi** [comment]
This was a limitation in Common.Logging (one adapter at a time) that is now fixed by introducing MultipleLogger adapter as mentioned here: https://github.com/net-commons/common-logging/issues/8

**Comment by RudeySH** [comment]
Okay, so my conclusion was incorrect, I didn't realize you can configure Common.Logging to use multiple adapters.

**Comment by amrlafi** [comment]
I updated the guide to include a reference to MultipleLogger.
